# Change 'comments' to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: 'millennial-3'

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-ID: 'UA-112060364-2'

menu:
- {name: 'Resume',             url: 'resume'}
- {name: 'About',              url: 'about'}
- {name: 'Painting',           url: 'painting'}
- {name: 'Contact',            url: 'contact'}


# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
- {icon: 'github', link:    'https://github.com/Cysuan'}
- {icon: 'redbook', link:   'https://www.xiaohongshu.com/user/profile/6000072c0000000001001943'}
- {icon: 'envelope', link:   'mailto:caisiyuanabi@163.com'}

# Customize site text
pagination:
  next_page: 'Newer'
  previous_page: 'Older'

post_date_prefix: 'Written on'
