# Change 'comments' to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: 'millennial-3'

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-ID: 'UA-112060364-2'

menu:
- {name: 'Interesting Facts',  url: 'facts'}
- {name: 'About',              url: 'about'}
- {name: 'Work',               url: 'works'}
- {name: 'Contact',            url: 'contact'}
- {name: 'Shop',               url: 'shop'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
- {icon: 'twitter', link:    'https://twitter.com/paululele'}
- {icon: 'redbook', link:   'https://www.xiaohongshu.com/user/profile/6000072c0000000001001943'}
- {icon: 'mastodon', link:  'https://m.cmx.im/@beautygranny'}
- {icon: 'envelope', link:   'mailto:caisiyuanabi@163.com'}
- {icon: 'rss-square', link: 'feed.xml'}
# - {icon: 'rss-square', link: 'rss-feed.xml'}

# Customize site text
pagination:
  next_page: 'Newer'
  previous_page: 'Older'

sharing_button_prompt: 'Feel free to share!'

related_posts: 'You may also enjoy...'

post_date_prefix: 'Written on'
